service: csv-serverless-lambda

provider:
  name: aws
  runtime: nodejs8.10
  stage: production
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "*"

functions:
  processCSV:
    name: processCSV
    handler: handler.processCSV
    events:
      - s3:
          bucket: input-csv-inuargnfiaughjkdsgnksjdb
          event: s3:ObjectCreated:*
          rules:
            - suffix: .csv
    environment:
      ARE_BUCKET: ${self:resources.Resources.are.Properties.BucketName}
      NODE_ENV: production

resources:
  Resources:
    are:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: output-are-nuvifshgfakdfjakdfkacvbf
