org: emsesc
app: serverless-syncfit
service: syncfit-serverless-lambda

provider:
  name: aws
  runtime: nodejs12.x
  stage: production
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "*"

functions:
  processTCX:
    name: processTCX
    handler: handler.processTCX
    events:
      - s3:
          bucket: syncfittcxfiles
          event: s3:ObjectCreated:*
          rules:
            - suffix: .txt
    environment:
      ZIPPED_DONE_BUCKET: ${self:resources.Resources.zippeddone.Properties.BucketName}
      NODE_ENV: production

resources:
  Resources:
    zippeddone:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: zippeddonebucket
